version: "3"

services:
  hr-worker-pg12:
    image: postgres:12-alpine
    container_name: "hr-worker-pg12"
    environment:
      - POSTGRES_PASSWORD=1234567
      - POSTGRES_DB=db_hr_worker
      - POSTGRES_USER=postgres
      - TZ=GMT
    ports:
      - 5434:5432

  hr-user-pg12:
    image: postgres:12-alpine
    container_name: "hr-user-pg12"
    environment:
      - POSTGRES_PASSWORD=1234567
      - POSTGRES_DB=db_hr_user
      - POSTGRES_USER=postgres
      - TZ=GMT
    ports:
      - 5433:5432
