spring:
  cloud:
    config:
      server:
        git:
          default-label: "main"
          uri: ${GITHUB_URI}
          passphrase: ${GITHUB_PASSPHRASE}
          skip-ssl-validation: true
          clone-on-start: true
          username: ${GITHUB_USER}
          password: ${GITHUB_PASS}
  application:
    name: "hr-config-server"
server:
  port: 8888

logging:
  file:
    name: ${LOG_PATH}/logs/config-server.log
