spring:
  application:
    name: hr-eureka-server
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  file:
    name: ${LOG_PATH}/logs/eureka-server.log